Repository auth0/auth0-java, pull requests merged in 2018-06, with the labels that each got.

#117 Add email-templates endpoints
  README.md
  src/main/java/com/auth0/client/mgmt/EmailTemplatesEntity.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/main/java/com/auth0/json/mgmt/EmailTemplate.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/EmailTemplatesEntityTest.java
  src/test/java/com/auth0/json/mgmt/EmailTemplateTest.java
  src/test/resources/mgmt/email_template.json
Labels: CH: Added

#120 Add Resend verification email functionality
  src/main/java/com/auth0/client/mgmt/JobsEntity.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/main/java/com/auth0/json/mgmt/jobs/Job.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
  src/test/java/com/auth0/json/mgmt/jobs/JobTest.java
  src/test/resources/mgmt/post_verification_email.json
Labels: CH: Added

#128 Deprecate ClientsEntity#list() method
  src/main/java/com/auth0/client/mgmt/ClientsEntity.java
Labels: CH: Deprecated

#129 Security fix and dependencies update
  build.gradle
Labels: CH: Security
