Repository auth0/auth0-java, pull requests merged in 2019-08, with the labels that each got.

#219 Update javadoc for expires_in
  src/main/java/com/auth0/json/auth/TokenHolder.java
Labels: tiny

#220 Find the right JDK version for Telemetry
  src/main/java/com/auth0/net/Telemetry.java
Labels: CH: Fixed, tiny

#221 Fix JavaDoc
  src/main/java/com/auth0/json/auth/TokenHolder.java
Labels: tiny

#222 Update dependencies
  build.gradle
Labels: CH: Security, tiny

#223 Release 1.14.2
  CHANGELOG.md
  README.md
Labels: tiny
