Repository auth0/auth0-java, pull requests merged in 2019-05, with the labels that each got.

#201 Dynamically obtain the project version for telemetry
  build.gradle
  src/main/java/com/auth0/BuildConfig.java
  src/main/java/com/auth0/net/TelemetryInterceptor.java
Labels: CH: Fixed

#206 Add metadata field to Connection object
  src/main/java/com/auth0/json/mgmt/Connection.java
  src/test/java/com/auth0/json/mgmt/ConnectionTest.java
  src/test/resources/mgmt/connection.json
  src/test/resources/mgmt/connections_list.json
Labels: CH: Added

#209 Bump dependencies and solve security issues
  build.gradle
Labels: CH: Security, tiny

#210 Release 1.13.3
  CHANGELOG.md
  README.md
Labels: tiny
