Repository auth0/auth0-java, pull requests merged in 2020-05, with the labels that each got.

#254 Add missing "sources" property to the Permission
  src/main/java/com/auth0/client/mgmt/UsersEntity.java
  src/main/java/com/auth0/json/mgmt/Permission.java
  src/main/java/com/auth0/json/mgmt/PermissionSource.java
  src/test/java/com/auth0/client/mgmt/RolesEntityTest.java
  src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
  src/test/java/com/auth0/json/mgmt/permissions/PermissionSourceTest.java
  src/test/java/com/auth0/json/mgmt/permissions/PermissionTest.java
  src/test/java/com/auth0/json/mgmt/permissions/PermissionsPageTest.java
Labels: CH: Added, small

#256 Add missing property last_password_reset
  src/main/java/com/auth0/json/mgmt/users/User.java
  src/test/java/com/auth0/client/mgmt/RolesEntityTest.java
  src/test/java/com/auth0/json/mgmt/users/UserTest.java
Labels: CH: Added

#259 Release 1.17.0
  CHANGELOG.md
  README.md
Labels: tiny

#258 Add signature verification classes
  build.gradle
  src/main/java/com/auth0/exception/IdTokenValidationException.java
  src/main/java/com/auth0/exception/PublicKeyProviderException.java
  src/main/java/com/auth0/utils/Asserts.java
  src/main/java/com/auth0/utils/tokens/HS256SignatureVerifier.java
  src/main/java/com/auth0/utils/tokens/PublicKeyProvider.java
  src/main/java/com/auth0/utils/tokens/RS256SignatureVerifier.java
  src/main/java/com/auth0/utils/tokens/SignatureVerifier.java
  src/test/java/com/auth0/utils/tokens/SignatureVerifierTest.java
  src/test/resources/keys/bad-public-rsa.pem
  src/test/resources/keys/public-rsa.pem
Labels: CH: Added, medium

#261 Explicit dependency on bouncycastle for tests
  build.gradle
Labels: tiny

#260 Add ID Token verifier API
  src/main/java/com/auth0/utils/tokens/IdTokenVerifier.java
  src/test/java/com/auth0/utils/tokens/IdTokenVerifierTest.java
Labels: CH: Added, medium

#262 Update to OkHttp 3.14.9
  build.gradle
  src/test/java/com/auth0/client/RecordedRequestMatcher.java
  src/test/java/com/auth0/client/mgmt/LogEventsEntityTest.java
  src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
Labels: CH: Changed, small

#263 Document ID Token Validation
  README.md
Labels: documentation, medium

#264 Release 1.18.0
  CHANGELOG.md
  README.md
Labels: tiny
