Repository auth0/auth0-java, pull requests merged in 2020-04, with the labels that each got.

#240 Add Rules Configs entity
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/main/java/com/auth0/client/mgmt/RulesConfigsEntity.java
  src/main/java/com/auth0/json/mgmt/RulesConfig.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/RulesConfigsEntityTest.java
  src/test/java/com/auth0/json/mgmt/RulesConfigTest.java
  src/test/resources/mgmt/rules_config.json
  src/test/resources/mgmt/rules_configs_list.json
Labels: CH: Added, medium

#242 Use char array for passwords
  .gitignore
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/json/mgmt/tickets/PasswordChangeTicket.java
  src/main/java/com/auth0/json/mgmt/users/User.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/json/mgmt/tickets/PasswordChangeTicketTest.java
  src/test/java/com/auth0/json/mgmt/users/UserTest.java
Labels: CH: Added, CH: Security

#243 deprecated string password APIs
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/json/mgmt/client/Client.java
  src/main/java/com/auth0/json/mgmt/tickets/PasswordChangeTicket.java
  src/main/java/com/auth0/json/mgmt/users/User.java
Labels: CH: Deprecated, small

#245 Make CreatedUser take the id from different properties
  src/main/java/com/auth0/json/auth/CreatedUser.java
  src/test/java/com/auth0/json/auth/CreatedUserTest.java
Labels: CH: Fixed, small

#247 Add Job "GET Status" endpoint
  src/main/java/com/auth0/client/mgmt/JobsEntity.java
  src/main/java/com/auth0/json/mgmt/jobs/Job.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
  src/test/java/com/auth0/json/mgmt/jobs/JobTest.java
  src/test/resources/mgmt/job.json
  src/test/resources/mgmt/job_post_verification_email.json
Labels: CH: Added, small

#241 Add Job "POST User Exports" endpoint
  src/main/java/com/auth0/client/mgmt/JobsEntity.java
  src/main/java/com/auth0/client/mgmt/filter/UsersExportFilter.java
  src/main/java/com/auth0/json/mgmt/jobs/Job.java
  src/main/java/com/auth0/json/mgmt/jobs/UsersExportField.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
  src/test/java/com/auth0/client/mgmt/filter/UsersExportFilterTest.java
  src/test/java/com/auth0/json/mgmt/jobs/JobTest.java
  src/test/java/com/auth0/json/mgmt/jobs/UsersExportFieldTest.java
  src/test/resources/mgmt/job_post_users_exports.json
Labels: CH: Added, medium

#244 Add missing "initiate_login_uri" property to Client
  src/main/java/com/auth0/json/mgmt/client/Client.java
  src/test/java/com/auth0/json/mgmt/client/ClientTest.java
Labels: CH: Added, small

#249 Add Job "POST User Imports" endpoint
  src/main/java/com/auth0/client/mgmt/JobsEntity.java
  src/main/java/com/auth0/client/mgmt/filter/UsersExportFilter.java
  src/main/java/com/auth0/client/mgmt/filter/UsersImportOptions.java
  src/main/java/com/auth0/json/mgmt/jobs/Job.java
  src/main/java/com/auth0/json/mgmt/jobs/JobSummary.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
  src/test/java/com/auth0/client/mgmt/filter/UsersImportOptionsTest.java
  src/test/java/com/auth0/json/mgmt/jobs/JobTest.java
  src/test/java/com/auth0/net/MultipartRequestTest.java
  src/test/resources/mgmt/job_post_users_imports.json
  src/test/resources/mgmt/job_post_users_imports_input.json
  src/test/resources/mgmt/multipart_sample.json
Labels: CH: Added, medium

#250 Add rotating_refresh_token to devicecredential token types.
  src/main/java/com/auth0/json/mgmt/DeviceCredentials.java
Labels: tiny

#251 Release 1.16.0
  CHANGELOG.md
  README.md
Labels: tiny
