Repository auth0/auth0-java, pull requests merged in 2020-11, with the labels that each got.

#311 Add unchecked warnings failures for src
  build.gradle
  src/main/java/com/auth0/exception/APIException.java
  src/test/java/com/auth0/exception/APIExceptionTest.java
Labels: CH: Fixed, medium

#313 Release 1.24.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#316 Use java8
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: CH: Changed

#319 Update to OkHttp 4
  build.gradle
  src/main/java/com/auth0/net/CustomRequest.java
  src/main/java/com/auth0/net/EmptyBodyRequest.java
  src/main/java/com/auth0/net/MultipartRequest.java
Labels: CH: Changed, review:small

#320 Release 1.25.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#317 Tidy up code
  .editorconfig
  .gitignore
  src/main/java/com/auth0/exception/APIException.java
  src/main/java/com/auth0/json/auth/UserInfo.java
  src/main/java/com/auth0/json/mgmt/EmailVerificationIdentity.java
  src/main/java/com/auth0/json/mgmt/Page.java
  src/main/java/com/auth0/json/mgmt/client/Addon.java
  src/main/java/com/auth0/json/mgmt/client/Addons.java
  src/main/java/com/auth0/json/mgmt/jobs/Job.java
  src/main/java/com/auth0/json/mgmt/jobs/JobSummary.java
  src/main/java/com/auth0/json/mgmt/jobs/UsersExportField.java
  src/main/java/com/auth0/json/mgmt/logstreams/LogStream.java
  src/main/java/com/auth0/json/mgmt/users/Identity.java
  src/main/java/com/auth0/json/mgmt/users/ProfileData.java
  src/main/java/com/auth0/json/mgmt/users/User.java
  src/test/java/com/auth0/client/RecordedRequestMatcher.java
  src/test/java/com/auth0/client/UrlMatcher.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/client/mgmt/BlacklistsEntityTest.java
  src/test/java/com/auth0/client/mgmt/ClientGrantsEntityTest.java
  src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java
  src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java
  src/test/java/com/auth0/client/mgmt/DeviceCredentialsEntityTest.java
  src/test/java/com/auth0/client/mgmt/EmailProviderEntityTest.java
  src/test/java/com/auth0/client/mgmt/EmailTemplatesEntityTest.java
  src/test/java/com/auth0/client/mgmt/GuardianEntityTest.java
  src/test/java/com/auth0/client/mgmt/ResourceServerEntityTest.java
  src/test/java/com/auth0/client/mgmt/RolesEntityTest.java
  src/test/java/com/auth0/client/mgmt/RulesConfigsEntityTest.java
  src/test/java/com/auth0/client/mgmt/RulesEntityTest.java
  src/test/java/com/auth0/client/mgmt/TicketsEntityTest.java
  src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
  src/test/java/com/auth0/client/mgmt/filter/ClientGrantsFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/ConnectionFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/DeviceCredentialsFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/FieldFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/GrantsFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/LogEventFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/PageFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/QueryFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/ResourceServersFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/RoleFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/RulesFilterTest.java
  src/test/java/com/auth0/client/mgmt/filter/UserFilterTest.java
  src/test/java/com/auth0/json/JsonTest.java
  src/test/java/com/auth0/json/auth/UserInfoTest.java
  src/test/java/com/auth0/json/mgmt/client/AddonTest.java
  src/test/java/com/auth0/json/mgmt/emailproviders/EmailProviderTest.java
  src/test/java/com/auth0/json/mgmt/tenants/TenantTest.java
  src/test/java/com/auth0/json/mgmt/users/IdentityTest.java
  src/test/java/com/auth0/json/mgmt/users/ProfileDataTest.java
  src/test/java/com/auth0/json/mgmt/users/UserTest.java
  src/test/java/com/auth0/net/CustomRequestTest.java
  src/test/java/com/auth0/net/TelemetryTest.java
  src/test/java/com/auth0/net/TokenRequestTest.java
  src/test/java/com/auth0/net/multipart/RecordedMultipartRequest.java
  src/test/java/com/auth0/utils/tokens/SignatureVerifierTest.java
Labels: CH: Fixed

#321 Add refresh token configuration object to client
  src/main/java/com/auth0/json/mgmt/client/Client.java
  src/main/java/com/auth0/json/mgmt/client/RefreshToken.java
  src/test/java/com/auth0/json/mgmt/client/ClientTest.java
  src/test/java/com/auth0/json/mgmt/client/RefreshTokenTest.java
Labels: CH: Added
