Repository auth0/auth0-java, pull requests merged in 2020-09, with the labels that each got.

#286 Add bot protection note to the readme
  README.md
Labels: small

#288 Revert "Add bot protection note to the readme"
  README.md
Labels: tiny

#292 Rename gradlew validation github action
  .github/workflows/gradle-wrapper-validation.yml
Labels: tiny

#293 Add support for identity field for email verification jobs and tickets
  src/main/java/com/auth0/client/mgmt/JobsEntity.java
  src/main/java/com/auth0/json/mgmt/EmailVerificationIdentity.java
  src/main/java/com/auth0/json/mgmt/tickets/EmailVerificationTicket.java
  src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
  src/test/java/com/auth0/json/mgmt/tickets/EmailVerificationTicketTest.java
Labels: CH: Added, medium

#294 Release 1.22.0
  CHANGELOG.md
  README.md
Labels: tiny
