Repository auth0/auth0-java, pull requests merged in 2021-04, with the labels that each got.

#342 Fix `NoSuchMethodError` when projects have OkHttp 3 dependency
  README.md
  src/main/java/com/auth0/net/CustomRequest.java
  src/main/java/com/auth0/net/EmptyBodyRequest.java
  src/main/java/com/auth0/net/MultipartRequest.java
Labels: CH: Fixed, review:small

#343 Release 1.28.1
  CHANGELOG.md
  README.md
Labels: review:tiny

#341 Add Organizations Management API Support [SDK-2437]
  src/main/java/com/auth0/client/mgmt/JobsEntity.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/main/java/com/auth0/client/mgmt/OrganizationsEntity.java
  src/main/java/com/auth0/client/mgmt/UsersEntity.java
  src/main/java/com/auth0/client/mgmt/filter/InvitationsFilter.java
  src/main/java/com/auth0/json/mgmt/client/Client.java
  src/main/java/com/auth0/json/mgmt/organizations/Branding.java
  src/main/java/com/auth0/json/mgmt/organizations/Colors.java
  src/main/java/com/auth0/json/mgmt/organizations/Connection.java
  src/main/java/com/auth0/json/mgmt/organizations/ConnectionsPageDeserializer.java
  src/main/java/com/auth0/json/mgmt/organizations/EnabledConnection.java
  src/main/java/com/auth0/json/mgmt/organizations/EnabledConnectionsPage.java
  src/main/java/com/auth0/json/mgmt/organizations/Invitation.java
  src/main/java/com/auth0/json/mgmt/organizations/InvitationsPage.java
  src/main/java/com/auth0/json/mgmt/organizations/InvitationsPageDeserializer.java
  src/main/java/com/auth0/json/mgmt/organizations/Invitee.java
  src/main/java/com/auth0/json/mgmt/organizations/Inviter.java
  src/main/java/com/auth0/json/mgmt/organizations/Member.java
  src/main/java/com/auth0/json/mgmt/organizations/Members.java
  src/main/java/com/auth0/json/mgmt/organizations/MembersPage.java
  src/main/java/com/auth0/json/mgmt/organizations/MembersPageDeserializer.java
  src/main/java/com/auth0/json/mgmt/organizations/Organization.java
  src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPage.java
  src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPageDeserializer.java
  src/main/java/com/auth0/json/mgmt/organizations/Roles.java
  src/main/java/com/auth0/json/mgmt/tickets/PasswordChangeTicket.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
  src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
  src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
  src/test/java/com/auth0/json/mgmt/client/ClientTest.java
  src/test/java/com/auth0/json/mgmt/organizations/EnabledConnectionsPageTest.java
  src/test/java/com/auth0/json/mgmt/organizations/EnabledConnectionsTest.java
  src/test/java/com/auth0/json/mgmt/organizations/InvitationTest.java
  src/test/java/com/auth0/json/mgmt/organizations/InvitationsPageTest.java
  src/test/java/com/auth0/json/mgmt/organizations/MembersPageTest.java
  src/test/java/com/auth0/json/mgmt/organizations/MembersTest.java
  src/test/java/com/auth0/json/mgmt/organizations/OrganizationsPageTest.java
  src/test/java/com/auth0/json/mgmt/organizations/OrganizationsTest.java
  src/test/java/com/auth0/json/mgmt/tickets/PasswordChangeTicketTest.java
  src/test/resources/mgmt/invitation.json
  src/test/resources/mgmt/invitations_list.json
  src/test/resources/mgmt/invitations_paged_list.json
  src/test/resources/mgmt/organization.json
  src/test/resources/mgmt/organization_connection.json
  src/test/resources/mgmt/organization_connections_list.json
  src/test/resources/mgmt/organization_connections_paged_list.json
  src/test/resources/mgmt/organization_member_roles_list.json
  src/test/resources/mgmt/organization_member_roles_paged_list.json
  src/test/resources/mgmt/organization_members_list.json
  src/test/resources/mgmt/organization_members_paged_list.json
  src/test/resources/mgmt/organizations_list.json
  src/test/resources/mgmt/organizations_paged_list.json
Labels: CH: Added, review:large

#345 [SDK-2456] Remove Organizations Beta Labelling
  README.md
Labels: review:tiny

#346 [SDK-2458] Updated guidance for working with tokens and organizations
  README.md
Labels: review:small

#344 Adds method to get an organization's enabled connection and update JavaDocs
  src/main/java/com/auth0/client/mgmt/OrganizationsEntity.java
  src/main/java/com/auth0/client/mgmt/UsersEntity.java
  src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
Labels: CH: Added, review:medium

#347 Release 1.29.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#348 Remove summary of Orgs feature from README
  README.md
Labels: review:tiny

#350 [SDK-2519] Remove commons-codec dependency
  build.gradle
  src/main/java/com/auth0/net/Telemetry.java
  src/test/java/com/auth0/net/TelemetryTest.java
Labels: CH: Changed, review:small

#352 [SDK-2537] Add missing parameters to Ticket entities
  src/main/java/com/auth0/json/mgmt/tickets/EmailVerificationTicket.java
  src/main/java/com/auth0/json/mgmt/tickets/PasswordChangeTicket.java
  src/test/java/com/auth0/json/mgmt/tickets/EmailVerificationTicketTest.java
  src/test/java/com/auth0/json/mgmt/tickets/PasswordChangeTicketTest.java
Labels: CH: Added, review:small

#353 Release 1.30.0
  CHANGELOG.md
  README.md
Labels: review:tiny
