Repository auth0/auth0-java, pull requests merged in 2021-07, with the labels that each got.

#357 [SDK-2622] Add expiresAt to token response
  src/main/java/com/auth0/json/auth/TokenHolder.java
  src/main/java/com/auth0/json/auth/TokenHolderDeserializer.java
  src/test/java/com/auth0/json/auth/TokenHolderTest.java
Labels: CH: Added, review:medium

#359 Release 1.32.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#362 [SDK-2664] Add support for checkpoint pagination
  src/main/java/com/auth0/client/mgmt/filter/PageFilter.java
  src/main/java/com/auth0/json/mgmt/Page.java
  src/main/java/com/auth0/json/mgmt/PageDeserializer.java
  src/main/java/com/auth0/json/mgmt/organizations/MembersPage.java
  src/main/java/com/auth0/json/mgmt/organizations/MembersPageDeserializer.java
  src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPage.java
  src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPageDeserializer.java
  src/main/java/com/auth0/json/mgmt/users/UsersPage.java
  src/main/java/com/auth0/json/mgmt/users/UsersPageDeserializer.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
  src/test/java/com/auth0/client/mgmt/RolesEntityTest.java
  src/test/java/com/auth0/client/mgmt/filter/PageFilterTest.java
  src/test/java/com/auth0/json/mgmt/organizations/MembersPageTest.java
  src/test/java/com/auth0/json/mgmt/organizations/OrganizationsPageTest.java
  src/test/java/com/auth0/json/mgmt/users/UsersPageTest.java
  src/test/resources/mgmt/organization_members_checkpoint_paged_list.json
  src/test/resources/mgmt/organizations_checkpoint_paged_list.json
  src/test/resources/mgmt/role_users_checkpoint_paged_list.json
Labels: CH: Added

#363 Deprecate unused constructors in Page implementations
  src/main/java/com/auth0/json/mgmt/organizations/MembersPage.java
  src/main/java/com/auth0/json/mgmt/organizations/MembersPageDeserializer.java
  src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPage.java
  src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPageDeserializer.java
  src/main/java/com/auth0/json/mgmt/users/UsersPage.java
  src/main/java/com/auth0/json/mgmt/users/UsersPageDeserializer.java
Labels: CH: Deprecated, review:small

#364 Release 1.33.0
  CHANGELOG.md
  README.md
Labels: tiny
