Repository auth0/auth0-java, pull requests merged in 2021-09, with the labels that each got.

#374 Updated page number to start at 0
  README.md
Labels: documentation

#375 Add user_name field to LogEvent
  src/main/java/com/auth0/json/mgmt/logevents/LogEvent.java
  src/test/java/com/auth0/json/mgmt/logevents/LogEventTest.java
Labels: CH: Fixed, review:tiny

#376 Release 1.34.1
  CHANGELOG.md
  README.md
Labels: review:tiny
