Repository auth0/auth0-java, pull requests merged in 2022-11, with the labels that each got.

#471 [SDK-3740] Enable LTS testing
  build.gradle
  settings.gradle
  src/test/java/com/auth0/net/TelemetryTest.java
Labels: CH: Added

#469 [SDK-3742] support Authorization Code + PKCE
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/client/auth/AuthorizeUrlBuilderTest.java
Labels: CH: Added

#467 [SDK-3741] Return response info
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/net/BaseRequest.java
  src/main/java/com/auth0/net/ExtendedBaseRequest.java
  src/main/java/com/auth0/net/Request.java
  src/main/java/com/auth0/net/Response.java
  src/main/java/com/auth0/net/ResponseImpl.java
  src/main/java/com/auth0/net/VoidRequest.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/client/mgmt/ActionsEntityTest.java
  src/test/java/com/auth0/client/mgmt/AttackProtectionEntityTest.java
  src/test/java/com/auth0/client/mgmt/BlacklistsEntityTest.java
  src/test/java/com/auth0/client/mgmt/BrandingEntityTest.java
  src/test/java/com/auth0/client/mgmt/ClientGrantsEntityTest.java
  src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java
  src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java
  src/test/java/com/auth0/client/mgmt/DeviceCredentialsEntityTest.java
  src/test/java/com/auth0/client/mgmt/EmailProviderEntityTest.java
  src/test/java/com/auth0/client/mgmt/EmailTemplatesEntityTest.java
  src/test/java/com/auth0/client/mgmt/GrantsEntityTest.java
  src/test/java/com/auth0/client/mgmt/GuardianEntityTest.java
  src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
  src/test/java/com/auth0/client/mgmt/KeysEntityTest.java
  src/test/java/com/auth0/client/mgmt/LogEventsEntityTest.java
  src/test/java/com/auth0/client/mgmt/LogStreamsEntityTest.java
  src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
  src/test/java/com/auth0/client/mgmt/ResourceServerEntityTest.java
  src/test/java/com/auth0/client/mgmt/RolesEntityTest.java
  src/test/java/com/auth0/client/mgmt/RulesConfigsEntityTest.java
  src/test/java/com/auth0/client/mgmt/RulesEntityTest.java
  src/test/java/com/auth0/client/mgmt/StatsEntityTest.java
  src/test/java/com/auth0/client/mgmt/TenantsEntityTest.java
  src/test/java/com/auth0/client/mgmt/TicketsEntityTest.java
  src/test/java/com/auth0/client/mgmt/UserBlocksEntityTest.java
  src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
  src/test/java/com/auth0/net/BaseRequestTest.java
  src/test/java/com/auth0/net/CreateUserRequestTest.java
  src/test/java/com/auth0/net/CustomRequestTest.java
  src/test/java/com/auth0/net/EmptyBodyRequestTest.java
  src/test/java/com/auth0/net/MultipartRequestTest.java
  src/test/java/com/auth0/net/RequestTest.java
  src/test/java/com/auth0/net/TokenRequestTest.java
  src/test/java/com/auth0/net/VoidRequestTest.java
Labels: CH: Breaking Change

#470 [SDK-3753] Use single ObjectMapper
  src/main/java/com/auth0/json/ObjectMapperProvider.java
  src/main/java/com/auth0/json/mgmt/PageDeserializer.java
  src/main/java/com/auth0/net/CustomRequest.java
  src/main/java/com/auth0/net/MultipartRequest.java
  src/main/java/com/auth0/net/Telemetry.java
  src/test/java/com/auth0/json/ObjectMapperProviderTest.java
Labels: CH: Changed

#475 [SDK-3777] Use builders to construct API client instances
  EXAMPLES.md
  README.md
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/main/java/com/auth0/net/client/DefaultHttpClient.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/client/mgmt/BaseMgmtEntityTest.java
  src/test/java/com/auth0/client/mgmt/ManagementAPITest.java
Labels: CH: Added

#476 [SDK-3837] Remove obsolete methods from API clients
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
Labels: CH: Removed

#477 [SDK-3836] deprecate API client constructors
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/client/mgmt/ManagementAPITest.java
Labels: CH: Deprecated, review:tiny
