Repository auth0/auth0-java, pull requests merged in 2022-10, with the labels that each got.

#464 Bump `com.fasterxml.jackson.core:jackson-databind` to 2.13.4.2
  build.gradle
Labels: CH: Security, dependencies, review:tiny

#459 [SDK-3680] README redesign
  EXAMPLES.md
  README.md
Labels: review:medium

#465 Bump `java-jwt` to 3.19.3
  build.gradle
Labels: CH: Security
