Repository auth0/auth0-java, pull requests merged in 2022-12, with the labels that each got.

#478 [SDK-3745] Update AuthAPI to not require client secret
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
Labels: CH: Changed, review:medium

#485 Simplify Request Customisation
  README.md
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/mgmt/ActionsEntity.java
  src/main/java/com/auth0/client/mgmt/BlacklistsEntity.java
  src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java
  src/main/java/com/auth0/client/mgmt/ClientsEntity.java
  src/main/java/com/auth0/client/mgmt/ConnectionsEntity.java
  src/main/java/com/auth0/client/mgmt/DeviceCredentialsEntity.java
  src/main/java/com/auth0/client/mgmt/EmailProviderEntity.java
  src/main/java/com/auth0/client/mgmt/EmailTemplatesEntity.java
  src/main/java/com/auth0/client/mgmt/GrantsEntity.java
  src/main/java/com/auth0/client/mgmt/JobsEntity.java
  src/main/java/com/auth0/client/mgmt/KeysEntity.java
  src/main/java/com/auth0/client/mgmt/LogEventsEntity.java
  src/main/java/com/auth0/client/mgmt/LogStreamsEntity.java
  src/main/java/com/auth0/client/mgmt/OrganizationsEntity.java
  src/main/java/com/auth0/client/mgmt/RequestBuilder.java
  src/main/java/com/auth0/client/mgmt/ResourceServerEntity.java
  src/main/java/com/auth0/client/mgmt/RolesEntity.java
  src/main/java/com/auth0/client/mgmt/RulesConfigsEntity.java
  src/main/java/com/auth0/client/mgmt/RulesEntity.java
  src/main/java/com/auth0/client/mgmt/StatsEntity.java
  src/main/java/com/auth0/client/mgmt/TenantsEntity.java
  src/main/java/com/auth0/client/mgmt/TicketsEntity.java
  src/main/java/com/auth0/client/mgmt/UserBlocksEntity.java
  src/main/java/com/auth0/client/mgmt/UsersEntity.java
  src/main/java/com/auth0/net/AuthRequest.java
  src/main/java/com/auth0/net/BaseRequest.java
  src/main/java/com/auth0/net/CreateUserRequest.java
  src/main/java/com/auth0/net/CustomRequest.java
  src/main/java/com/auth0/net/CustomizableRequest.java
  src/main/java/com/auth0/net/EmptyBodyRequest.java
  src/main/java/com/auth0/net/ExtendedBaseRequest.java
  src/main/java/com/auth0/net/FormDataRequest.java
  src/main/java/com/auth0/net/MultipartRequest.java
  src/main/java/com/auth0/net/Request.java
  src/main/java/com/auth0/net/SignUpRequest.java
  src/main/java/com/auth0/net/TokenRequest.java
  src/main/java/com/auth0/net/VoidRequest.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/net/BaseRequestTest.java
  src/test/java/com/auth0/net/CustomRequestTest.java
  src/test/java/com/auth0/net/RequestTest.java
  src/test/java/com/auth0/net/SignUpRequestTest.java
Labels: CH: Removed, CH: Breaking Change

#486 Use TokenProvider instead of plain string token
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/mgmt/ActionsEntity.java
  src/main/java/com/auth0/client/mgmt/AttackProtectionEntity.java
  src/main/java/com/auth0/client/mgmt/BaseManagementEntity.java
  src/main/java/com/auth0/client/mgmt/BlacklistsEntity.java
  src/main/java/com/auth0/client/mgmt/BrandingEntity.java
  src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java
  src/main/java/com/auth0/client/mgmt/ClientsEntity.java
  src/main/java/com/auth0/client/mgmt/ConnectionsEntity.java
  src/main/java/com/auth0/client/mgmt/DeviceCredentialsEntity.java
  src/main/java/com/auth0/client/mgmt/EmailProviderEntity.java
  src/main/java/com/auth0/client/mgmt/EmailTemplatesEntity.java
  src/main/java/com/auth0/client/mgmt/GrantsEntity.java
  src/main/java/com/auth0/client/mgmt/GuardianEntity.java
  src/main/java/com/auth0/client/mgmt/JobsEntity.java
  src/main/java/com/auth0/client/mgmt/KeysEntity.java
  src/main/java/com/auth0/client/mgmt/LogEventsEntity.java
  src/main/java/com/auth0/client/mgmt/LogStreamsEntity.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/main/java/com/auth0/client/mgmt/OrganizationsEntity.java
  src/main/java/com/auth0/client/mgmt/RequestBuilder.java
  src/main/java/com/auth0/client/mgmt/ResourceServerEntity.java
  src/main/java/com/auth0/client/mgmt/RolesEntity.java
  src/main/java/com/auth0/client/mgmt/RulesConfigsEntity.java
  src/main/java/com/auth0/client/mgmt/RulesEntity.java
  src/main/java/com/auth0/client/mgmt/SimpleTokenProvider.java
  src/main/java/com/auth0/client/mgmt/StatsEntity.java
  src/main/java/com/auth0/client/mgmt/TenantsEntity.java
  src/main/java/com/auth0/client/mgmt/TicketsEntity.java
  src/main/java/com/auth0/client/mgmt/TokenProvider.java
  src/main/java/com/auth0/client/mgmt/UserBlocksEntity.java
  src/main/java/com/auth0/client/mgmt/UsersEntity.java
  src/main/java/com/auth0/net/BaseRequest.java
  src/main/java/com/auth0/net/EmptyBodyRequest.java
  src/main/java/com/auth0/net/MultipartRequest.java
  src/main/java/com/auth0/net/SignUpRequest.java
  src/main/java/com/auth0/net/TokenRequest.java
  src/main/java/com/auth0/net/VoidRequest.java
  src/test/java/com/auth0/client/mgmt/ManagementAPITest.java
  src/test/java/com/auth0/client/mgmt/SimpleTokenProviderTest.java
  src/test/java/com/auth0/net/BaseRequestTest.java
  src/test/java/com/auth0/net/EmptyBodyRequestTest.java
  src/test/java/com/auth0/net/MultipartRequestTest.java
  src/test/java/com/auth0/net/VoidRequestTest.java
Labels: CH: Changed, review:large

#489 Remove deprecated methods
  src/main/java/com/auth0/client/HttpOptions.java
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java
  src/main/java/com/auth0/client/mgmt/ClientsEntity.java
  src/main/java/com/auth0/client/mgmt/ConnectionsEntity.java
  src/main/java/com/auth0/client/mgmt/GrantsEntity.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/main/java/com/auth0/client/mgmt/ResourceServerEntity.java
  src/main/java/com/auth0/client/mgmt/RulesEntity.java
  src/main/java/com/auth0/json/mgmt/guardian/EnrollmentTicket.java
  src/main/java/com/auth0/json/mgmt/guardian/SNSFactorProvider.java
  src/main/java/com/auth0/json/mgmt/guardian/TwilioFactorProvider.java
  src/main/java/com/auth0/net/RateLimitInterceptor.java
  src/test/java/com/auth0/client/HttpOptionsTest.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/client/mgmt/ClientGrantsEntityTest.java
  src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java
  src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java
  src/test/java/com/auth0/client/mgmt/GrantsEntityTest.java
  src/test/java/com/auth0/client/mgmt/ManagementAPITest.java
  src/test/java/com/auth0/client/mgmt/ResourceServerEntityTest.java
  src/test/java/com/auth0/client/mgmt/RulesEntityTest.java
  src/test/java/com/auth0/json/mgmt/guardian/SNSFactorProviderTest.java
  src/test/java/com/auth0/json/mgmt/guardian/TwilioFactorProviderTest.java
Labels: CH: Breaking Change

#490 Remove Request async default implementation
  src/main/java/com/auth0/net/Request.java
  src/test/java/com/auth0/net/RequestTest.java
Labels: CH: Changed

#491 [SDK-3875] Added migration guide
  MIGRATION_GUIDE.md
Labels: CH: Added
