Repository auth0/auth0-java, pull requests merged in 2022-04, with the labels that each got.

#417 Update OkHttp to address CVE-2021-0341
  build.gradle
Labels: CH: Security

#418 Release 1.40.2
  CHANGELOG.md
  README.md
Labels: review:tiny

#420 Fix double-encoding of log event filter query param
  src/main/java/com/auth0/client/mgmt/UsersEntity.java
  src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
Labels: CH: Fixed, review:small

#421 Do not cast error values to String
  src/main/java/com/auth0/exception/APIException.java
  src/test/java/com/auth0/exception/APIExceptionTest.java
Labels: CH: Fixed, review:medium
