Repository auth0/auth0-java, pull requests merged in 2022-02, with the labels that each got.

#403 Release 1.38.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#381 Feature/reduce duplication
  src/main/java/com/auth0/client/mgmt/BaseManagementEntity.java
  src/main/java/com/auth0/client/mgmt/GuardianEntity.java
  src/main/java/com/auth0/client/mgmt/RequestBuilder.java
  src/test/java/com/auth0/client/mgmt/ClientGrantsEntityTest.java
Labels: CH: Changed

#405 [SDK-3116] Add support for Attack Protection APIs
  src/main/java/com/auth0/client/mgmt/AttackProtectionEntity.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/main/java/com/auth0/json/mgmt/attackprotection/BreachedPassword.java
  src/main/java/com/auth0/json/mgmt/attackprotection/BruteForceConfiguration.java
  src/main/java/com/auth0/json/mgmt/attackprotection/Stage.java
  src/main/java/com/auth0/json/mgmt/attackprotection/StageEntry.java
  src/main/java/com/auth0/json/mgmt/attackprotection/SuspiciousIPThrottlingConfiguration.java
  src/test/java/com/auth0/client/MockServer.java
  src/test/java/com/auth0/client/mgmt/AttackProtectionEntityTest.java
  src/test/java/com/auth0/json/mgmt/attackprotection/BreachedPasswordTest.java
  src/test/java/com/auth0/json/mgmt/attackprotection/BruteForceConfigurationTest.java
  src/test/java/com/auth0/json/mgmt/attackprotection/SuspiciousIPThrottlingConfigurationTest.java
  src/test/resources/mgmt/breached_password_settings.json
  src/test/resources/mgmt/brute_force_configuration.json
  src/test/resources/mgmt/suspicious_ip_throttling_configuration.json
Labels: CH: Added, review:medium

#406 [SDK-3098] Fix documentation for authorize and logout URL creation
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java
  src/main/java/com/auth0/client/auth/LogoutUrlBuilder.java
Labels: review:small

#407 [ESD-18148] Update UsersEntity.java
  src/main/java/com/auth0/client/mgmt/UsersEntity.java
Labels: review:tiny

#408 Release 1.39.0
  CHANGELOG.md
  README.md
Labels: review:tiny
