Repository auth0/auth0-java, pull requests merged in 2022-03, with the labels that each got.

#411 Bump `jackson-databind` dependency to 2.13.2
  build.gradle
Labels: CH: Security, dependencies, review:tiny

#413 Update java-jwt dependency
  build.gradle
Labels: CH: Changed, dependencies, review:tiny

#412 Release 1.40.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#414 Security: Bump `jackson-databind` to 2.13.2.2
  build.gradle
Labels: CH: Security, dependencies, review:tiny

#415 Bump java-jwt to 3.19.1
  build.gradle
Labels: CH: Security, review:tiny
