Repository auth0/auth0-java, pull requests merged in 2022-01, with the labels that each got.

#391 Release 1.36.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#394 Update jackson dependency
  build.gradle
Labels: CH: Security

#395 Release 1.36.1
  CHANGELOG.md
  README.md
Labels: review:tiny

#392 Improve logging
  src/main/java/com/auth0/client/HttpOptions.java
  src/main/java/com/auth0/client/LoggingOptions.java
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
  src/test/java/com/auth0/client/auth/AuthAPITest.java
  src/test/java/com/auth0/client/mgmt/ManagementAPITest.java
Labels: CH: Added

#396 Deprecate setLoggingEnabled on API clients
  src/main/java/com/auth0/client/auth/AuthAPI.java
  src/main/java/com/auth0/client/mgmt/ManagementAPI.java
Labels: CH: Deprecated, review:tiny

#397 Add support for Connection realms
  src/main/java/com/auth0/json/mgmt/Connection.java
  src/test/java/com/auth0/json/mgmt/ConnectionTest.java
Labels: CH: Added, review:small

#398 Release 1.37.0
  CHANGELOG.md
  README.md
Labels: review:tiny
